version: '0.2'
language: en
files:
  - "**/*.{js,jsx,ts,tsx,mjs,cjs,svelte,html,css,scss,md,mdx,json,jsonc,yaml,ym\
    l}"
  - src/**/*
  - e2e/**/*
  - stories/**/*
ignorePaths:
  - .vscode/**.*
  - node_modules/**
  - build/**
  - .svelte-kit/**
  - dist/**
  - coverage/**
  - test-results/**
  - project.inlang/**
  - '**/*.d.ts'
  - '**/*.map'
  - '**/*.min.js'
  - src/lib/paraglide/*.js
  - '**/*.svg'
  - storybook-static/**/*
  - .git/**/*
  - .gitignore
  - .scannerwork/**/*
  - google*.html
words:
  - autodocs
  - autorestart
  - bttf
  - customise
  - darkmode
  - decensor
  - delorean
  - Dsonar
  - EDITMSG
  - ELEVENLABS
  - elif
  - enablejsapi
  - Groot
  - Gump
  - Hotspots
  - ianvs
  - inlang
  - isready
  - joshuafolkken
  - LEFTHOOK
  - Lorean
  - Maguire
  - mcfly
  - mdsvex
  - mischeck
  - modestbranding
  - mysecretpassword
  - Nemo
  - Notting
  - octocat
  - oslojs
  - paraglide
  - pgdata
  - Qube
  - scannerwork
  - sonarcloud
  - sonarjs
  - sonarqube
  - Stylesheet
  - Vercel
  - vibing
  - Vite
  - Caddyfile
  - joshuastudio
  - fastcgi
  - ENDSSH
  - keygen
  - appleboy
