version: '0.2'
language: en
files:
  - src/**/*
  - e2e/**/*
  - stories/**/*
ignorePaths:
  - .vscode/**
  - node_modules/**
  - build/**
  - .svelte-kit/**
  - dist/**
  - coverage/**
  - test-results/**
  - project.inlang/**
  - '**/*.d.ts'
  - '**/*.map'
  - '**/*.min.js'
  - src/lib/paraglide/*.js
  - '**/*.svg'
  - .git/**/*
  - .gitignore
  - .scannerwork/**/*
  - google*.html
  - 'pnpm-lock.yaml'
  - '.env*'
words:
  - appleboy
  - autodocs
  - autorestart
  - bttf
  - Caddyfile
  - customise
  - darkmode
  - decensor
  - delorean
  - Dsonar
  - EDITMSG
  - ELEVENLABS
  - elif
  - enablejsapi
  - ENDSSH
  - fastcgi
  - FOLKKEN
  - Groot
  - gsub
  - Gump
  - Hotspots
  - ianvs
  - inlang
  - isready
  - joshuafolkken
  - joshuastudio
  - keygen
  - LEFTHOOK
  - Lorean
  - Maguire
  - mcfly
  - mischeck
  - modestbranding
  - mysecretpassword
  - Nemo
  - Notting
  - octocat
  - oslojs
  - paraglide
  - pgdata
  - Qube
  - redir
  - Referer
  - scannerwork
  - sonarcloud
  - sonarjs
  - sonarqube
  - Stylesheet
  - tonumber
  - tostring
  - Vercel
  - vibing
  - Vite
  - zstd
  - aikidosec
  - unrs
  - esbuild
  - lefthook
  - cooldown
